on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
jobs:
  QA:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:9.6
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Setup project
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: 1.10.2
          otp-version: 22.2
      - name: Install Hex dependencies
        run: cd portfolio && mix deps.get
      - name: Run linter
        run: cd portfolio && mix credo
      - name: Run tests
        run: cd portfolio && mix test